### ISSUE TITLE
Generator ile yeni proje oluştururken, CorePackages klasörü oluşturulamıyor

### ISSUE THREAD

**Issue by kdeliaci** [kodlamaio-projects/nArchitecture.Gen#13]
.Net 8 ile generator, corePackages klasörünü oluşturmuyor. Herhangi bir hata vermiyor klasörler kontrol edilirken farkedildi

**Comment by meminozturkk** [comment]
çözümünü buldun mu?

**Comment by halitkalayci** [comment]
Merhabalar,

Yeni sürümlerle beraber artık NArchitecture Core paketleri NuGet üzerine taşınarak projelerde bağımlılık olarak ekleniyor. Dolayısıyla her projede CorePackages klasörü ve içeriğine ihtiyaç yok. Gerek görüldüğü kısımlarda bu paketlerdeki kodları override/extend ederek custom kodlar geliştirebilirsiniz.

bknz: https://www.nuget.org/profiles/Kodlama.io
