### ISSUE TITLE
Logout methodu eksikliği

### ISSUE THREAD

**Issue by Trkrkrl** [kodlamaio-projects/nArchitecture.Gen#16]
Generated apilerimizde Logout methodu yok. AccessTokeni revoke da edemiyoruz. Bu özellik eklenmeli diye düşünüyorum

**Comment by halitkalayci** [comment]
Hello, sorry for the late reply. This project uses `JWT` as the default authentication scheme. JWT is stateless, so it does not require a `logout` method. However, for a revoking strategy, you can use blacklisting with some custom implementations.
