### ISSUE TITLE
For MacOs

### ISSUE THREAD

**Issue by muratfirtina** [kodlamaio-projects/nArchitecture.Gen#6]
nArchGen i Mac veya unix  bilgisayarlarda çalıştırmak için path yollarını gösteren "\" işaretlerinin "/" ile değiştirilmesi gerekiyor. fakat nasıl yapabileceğimi bulamadım. yardımcı olursanız sevinirim.

**Comment by ahmet-cetinkaya** [comment]
It will fix with #3 pull request 🛠.
