### ISSUE TITLE
Cannot run Update-Database

### ISSUE THREAD

**Issue by osd1syc** [kodlamaio-projects/nArchitecture.Gen#9]
The tool does not allow running Update-Database command because DbContext is not configured for the connection string. The closed suggestion of running DesignTimeDbContextFactory does not work. Please resolve this error.

**Comment by Ertuss** [comment]
Try like this

public partial class BaseDbContext : DbContext
{
    public BaseDbContext()
    {
    }

    public BaseDbContext(DbContextOptions<BaseDbContext> options)
        : base(options)
    {
    }


    public DbSet<EmailAuthenticator<int, int>> EmailAuthenticators { get; set; }
    public DbSet<OperationClaim<int, int>> OperationClaims { get; set; }
    public DbSet<OtpAuthenticator<int, int>> OtpAuthenticators { get; set; }
    public DbSet<RefreshToken<int, int>> RefreshTokens { get; set; }
    public DbSet<User<int, int>> Users { get; set; }
    public DbSet<UserOperationClaim<int, int>> UserOperationClaims { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseNpgsql("***");
    }

}

**Comment by ahmet-cetinkaya** [comment]
> The tool does not allow running Update-Database command because DbContext is not configured for the connection string. The closed suggestion of running DesignTimeDbContextFactory does not work. Please resolve this error.

The project first works with the InMemory database. You can include EF Context according to the database management system you use. And create a migration and then create your database.

Example:
```cs
namespace Persistence;

public static class PersistenceServiceRegistration
{
    public static IServiceCollection AddPersistenceServices(this IServiceCollection services, IConfiguration configuration)
    {
        services.AddDbContext<BaseDbContext>(options => options.UseNpgsql(connectionString: configuration.GetConnectionString("BaseDb")));
        // ...
     }
}
```

**Comment by osd1syc** [comment]
> > The tool does not allow running Update-Database command because DbContext is not configured for the connection string. The closed suggestion of running DesignTimeDbContextFactory does not work. Please resolve this error.
> 
> The project first works with the InMemory database. You can include EF Context according to the database management system you use. And create a migration and then create your database.
> 
> Example for PostgreSQL:
> 
> ```cs
> namespace Persistence;
> 
> public static class PersistenceServiceRegistration
> {
>     public static IServiceCollection AddPersistenceServices(this IServiceCollection services, IConfiguration configuration)
>     {
>         services.AddDbContext<BaseDbContext>(options => options.UseNpgsql(connectionString: configuration.GetConnectionString("BaseDb")));
>         // ...
>      }
> }
> ```

This works perfectively.
